# Generated by Django 5.2.3 on 2025-06-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendedQuiz',
            new_name='AttendedTableQuiz',
        ),
    ]
