# Generated by Django 5.2.3 on 2025-06-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_attendedquiz_attendedtablequiz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendedTableQuiz',
            new_name='AttendedQuizTable',
        ),
        migrations.AlterField(
            model_name='questiontable',
            name='answer',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1),
        ),
    ]
