# Generated by Django 5.2.3 on 2025-06-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiztable_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendedquiztable',
            name='first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendedquiztable',
            name='second',
            field=models.BooleanField(default=False),
        ),
    ]
